services:
  - type: web
    name: wot-battle-analyzer
    env: python
    buildCommand: chmod +x build.sh && ./build.sh && pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 'app:app'
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PATH
        value: /usr/bin:$PATH
    autoDeploy: true 