services:
  - type: web
    name: wot-battle-analyzer
    env: python
    buildCommand: chmod +x build.sh && ./build.sh && pip install -r requirements.txt
    startCommand: python -m gunicorn --config gunicorn.conf.py --worker-class eventlet app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PATH
        value: /opt/render/project/src/chrome/chrome-linux:/opt/render/project/src/chromedriver:/usr/local/bin:/usr/bin:$PATH
      - key: CHROME_BIN
        value: /opt/render/project/src/chrome/chrome-linux/chrome
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PORT
        value: "10000"
      - key: FLASK_ENV
        value: "production"
      - key: FLASK_APP
        value: "app.py"
    healthCheckPath: /
    autoDeploy: true 