services:
  - type: web
    name: wot-battle-analyzer
    env: python
    buildCommand: chmod +x build.sh && ./build.sh && pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PATH
        value: /opt/render/project/src/chrome/chrome-linux:/opt/render/project/src/chromedriver:/usr/local/bin:/usr/bin:$PATH
      - key: CHROME_BIN
        value: /opt/render/project/src/chrome/chrome-linux/chrome
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PORT
        value: "10000"
    autoDeploy: true 